### ISSUE TITLE
how get getvalue(x), getvalue(y), getvalue(w) of farmer problem

### ISSUE THREAD

**Issue by Esnilg** [Argonne-National-Laboratory/DSP#22]
Hi,

I'm running the model of the problem farmer and I do not know how to get the values ​​of the variables

I used:  status = solve(m, solve_type = :Dual)

![captura de pantalla de 2017-12-16 13-48-45](https://user-images.githubusercontent.com/32929965/34072542-ef537c62-e267-11e7-8e61-e38444eb36e2.png)

![captura de pantalla de 2017-12-16 13-49-01](https://user-images.githubusercontent.com/32929965/34072541-e8ebcf5a-e267-11e7-8a76-cd2eca257057.png)

**Comment by kibaekkim** [comment]
Sorry for the late response. You can get the primal solution by ``getprimvalue()`` or ``getvalue(x)`` for the first-stage variable values. However, you cannot use ``getvalue(y)`` or ``getvalue(w)``, because the variables names were overwritten. There may be a way to access the second-stage variable values more conveniently, which would require some effort on Julia script.
