### ISSUE TITLE
DSIP instalation: OsiSpxSolverInterface.hpp

### ISSUE THREAD

**Issue by juantorres91** [Argonne-National-Laboratory/DSP#23]
Hi Kibaek and Victor,

I'm re-installing DSP to test to evaluate the performance using CPLEX as solver. I'm having problems installing it, I did the following steps on the installation 

- set the path to libcplex.a and cplex.h in USERconfig file
- made  ma27 and pointed the path to the ma27lib
- made scip-3.1.1 without ZIMPL ,
-set the path to scip, scip_lib and soplex

I'm having the following problem 

![image](https://user-images.githubusercontent.com/20445793/34188758-000ef75c-e506-11e7-8cee-c8f1fca8a931.png)

I hope you can assist me with this issue,

Best regards,

Juan José

**Comment by kibaekkim** [comment]
I did not notice that the issue was opened. @juantorres91 and I resolved the issue by exchanging several emails. Long story short, I have fixed bugs in ``CMakeLists.txt`` files. I have also confirmed that ``DSP`` cannot be compiled with ``SCIP`` version 4 or higher, because of the significant changes in ``SOPLEX``.
